### ISSUE TITLE
The website loads very slowly

### ISSUE THREAD

**Issue by moul** [parisp2p/p2p.paris#38]
The event images are too big and need to be resized

**Comment by gorhgorh** [comment]
yep, full images are used for the list view, I'll make some thumbs / optimise the big ones, good issue to check how hugo works

**Comment by alexsland** [comment]
I haven't optimized the event images yet because has I said in the PR I'm going to replace them, I intend to optimize the images once it's done. I did this quickly and just used the images I made for meetup, but I need blank images and will add the text on them trough html. I will do it tomorrow probably.

**Comment by gorhgorh** [comment]
ok, I already made the changes to use thumbnails if you are interested in a pr for that

**Comment by alexsland** [comment]
Ok great @gorhgorh, go ahead.
I will just have to change the images then :)

**Comment by moul** [comment]
@cdeleeuwe can you help to make the resize auto instead of having to manually resize images? 

I prefer to rely on hugo for this and profit that hugo knows the image size to have a fixed-height div while the image is still loading

**Comment by alexsland** [comment]
Yes @moul I know we should do this auto and it is what I was planning to do I just believed it is was @gorhgorh was doing...

**Comment by cdeleeuwe** [comment]
@moul , yes sure, I can do this :). Will make a PR in a bit.

**Comment by moul** [comment]
looks good, thanks!
